[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "labUtils"
version = "0.0.1"
description = "ifferent python snippet for lab."
readme = "README.md"

dependencies = [
    "numpy",
    "pandas",
    "scipy",
    "addict",
    "statsmodels",
    "matplotlib",
    "openpyxl",
]
